cc_binary(
    name = "devapi_test",
    srcs = ["devapi_test.cc"],
    deps = [
        "//:mysql-connector-cpp",
    ],
    copts = [
        "-std=c++20",
    ],
    linkopts = [
    ],
)

cc_binary(
    name = "test",
    srcs = ["test.cpp"],
    deps = [

    ],
     copts = [
        "-std=c++20",
    ],
)